name: SampleGitHubAction

on:
 push:
    branches:
        - main
 pull_request:
    branches:
        - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Hello World
      run: echo "Hello Sarit"
      shell: zsh

    - name: Goodbye 
      run: echo "Goodbye Sarit"
      shell: zsh
