name: SampleGitHubAction

on:
 push:
    branches:
        - main
 pull_request:
    branches:
        - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Hello World
      run: echo "${{ toJSON(github)}}"
      shell: bash

    - name: Goodbye 
      run: echo "${{toJSON(job)}}"
      shell: bash
